// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#include "messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace myproto {
PROTOBUF_CONSTEXPR MotorCommand::MotorCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.left_motor_speed_)*/0
  , /*decltype(_impl_.right_motor_speed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MotorCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MotorCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MotorCommandDefaultTypeInternal() {}
  union {
    MotorCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MotorCommandDefaultTypeInternal _MotorCommand_default_instance_;
PROTOBUF_CONSTEXPR ArmCommand::ArmCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_dir_)*/0
  , /*decltype(_impl_.y_dir_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ArmCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArmCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArmCommandDefaultTypeInternal() {}
  union {
    ArmCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArmCommandDefaultTypeInternal _ArmCommand_default_instance_;
PROTOBUF_CONSTEXPR IntakeCommand::IntakeCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.speed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IntakeCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntakeCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntakeCommandDefaultTypeInternal() {}
  union {
    IntakeCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntakeCommandDefaultTypeInternal _IntakeCommand_default_instance_;
PROTOBUF_CONSTEXPR ActuatorCommand::ActuatorCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActuatorCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActuatorCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActuatorCommandDefaultTypeInternal() {}
  union {
    ActuatorCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActuatorCommandDefaultTypeInternal _ActuatorCommand_default_instance_;
PROTOBUF_CONSTEXPR Wrapper::Wrapper(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct WrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WrapperDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WrapperDefaultTypeInternal() {}
  union {
    Wrapper _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WrapperDefaultTypeInternal _Wrapper_default_instance_;
}  // namespace myproto
static ::_pb::Metadata file_level_metadata_messages_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_messages_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_messages_2eproto = nullptr;

const uint32_t TableStruct_messages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myproto::MotorCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myproto::MotorCommand, _impl_.left_motor_speed_),
  PROTOBUF_FIELD_OFFSET(::myproto::MotorCommand, _impl_.right_motor_speed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myproto::ArmCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myproto::ArmCommand, _impl_.x_dir_),
  PROTOBUF_FIELD_OFFSET(::myproto::ArmCommand, _impl_.y_dir_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myproto::IntakeCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myproto::IntakeCommand, _impl_.speed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myproto::ActuatorCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myproto::ActuatorCommand, _impl_.id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myproto::Wrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::myproto::Wrapper, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myproto::Wrapper, _impl_.type_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::myproto::Wrapper, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::myproto::MotorCommand)},
  { 8, -1, -1, sizeof(::myproto::ArmCommand)},
  { 16, -1, -1, sizeof(::myproto::IntakeCommand)},
  { 23, -1, -1, sizeof(::myproto::ActuatorCommand)},
  { 30, -1, -1, sizeof(::myproto::Wrapper)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::myproto::_MotorCommand_default_instance_._instance,
  &::myproto::_ArmCommand_default_instance_._instance,
  &::myproto::_IntakeCommand_default_instance_._instance,
  &::myproto::_ActuatorCommand_default_instance_._instance,
  &::myproto::_Wrapper_default_instance_._instance,
};

const char descriptor_table_protodef_messages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016messages.proto\022\007myproto\"C\n\014MotorComman"
  "d\022\030\n\020left_motor_speed\030\001 \001(\002\022\031\n\021right_mot"
  "or_speed\030\002 \001(\002\"*\n\nArmCommand\022\r\n\005x_dir\030\001 "
  "\001(\002\022\r\n\005y_dir\030\002 \001(\002\"\036\n\rIntakeCommand\022\r\n\005s"
  "peed\030\001 \001(\002\"\035\n\017ActuatorCommand\022\n\n\002id\030\001 \001("
  "\005\"\374\001\n\007Wrapper\022\"\n\004type\030\001 \001(\0162\024.myproto.Me"
  "ssageType\022.\n\rmotor_command\030\002 \001(\0132\025.mypro"
  "to.MotorCommandH\000\022*\n\013arm_command\030\003 \001(\0132\023"
  ".myproto.ArmCommandH\000\0220\n\016intake_command\030"
  "\004 \001(\0132\026.myproto.IntakeCommandH\000\0224\n\020actua"
  "tor_command\030\005 \001(\0132\030.myproto.ActuatorComm"
  "andH\000B\t\n\007payload*h\n\013MessageType\022\013\n\007UNKNO"
  "WN\020\000\022\021\n\rMOTOR_COMMAND\020\001\022\017\n\013ARM_COMMAND\020\002"
  "\022\022\n\016INTAKE_COMMAND\020\003\022\024\n\020ACTUATOR_COMMAND"
  "\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_messages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false, false, 570, descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_messages_2eproto::offsets,
    file_level_metadata_messages_2eproto, file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_messages_2eproto_getter() {
  return &descriptor_table_messages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_messages_2eproto(&descriptor_table_messages_2eproto);
namespace myproto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_messages_2eproto);
  return file_level_enum_descriptors_messages_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class MotorCommand::_Internal {
 public:
};

MotorCommand::MotorCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myproto.MotorCommand)
}
MotorCommand::MotorCommand(const MotorCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MotorCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.left_motor_speed_){}
    , decltype(_impl_.right_motor_speed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.left_motor_speed_, &from._impl_.left_motor_speed_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.right_motor_speed_) -
    reinterpret_cast<char*>(&_impl_.left_motor_speed_)) + sizeof(_impl_.right_motor_speed_));
  // @@protoc_insertion_point(copy_constructor:myproto.MotorCommand)
}

inline void MotorCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.left_motor_speed_){0}
    , decltype(_impl_.right_motor_speed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MotorCommand::~MotorCommand() {
  // @@protoc_insertion_point(destructor:myproto.MotorCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MotorCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MotorCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MotorCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:myproto.MotorCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.left_motor_speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.right_motor_speed_) -
      reinterpret_cast<char*>(&_impl_.left_motor_speed_)) + sizeof(_impl_.right_motor_speed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MotorCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float left_motor_speed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.left_motor_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float right_motor_speed = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.right_motor_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MotorCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myproto.MotorCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float left_motor_speed = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_motor_speed = this->_internal_left_motor_speed();
  uint32_t raw_left_motor_speed;
  memcpy(&raw_left_motor_speed, &tmp_left_motor_speed, sizeof(tmp_left_motor_speed));
  if (raw_left_motor_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_left_motor_speed(), target);
  }

  // float right_motor_speed = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_right_motor_speed = this->_internal_right_motor_speed();
  uint32_t raw_right_motor_speed;
  memcpy(&raw_right_motor_speed, &tmp_right_motor_speed, sizeof(tmp_right_motor_speed));
  if (raw_right_motor_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_right_motor_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myproto.MotorCommand)
  return target;
}

size_t MotorCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myproto.MotorCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float left_motor_speed = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_motor_speed = this->_internal_left_motor_speed();
  uint32_t raw_left_motor_speed;
  memcpy(&raw_left_motor_speed, &tmp_left_motor_speed, sizeof(tmp_left_motor_speed));
  if (raw_left_motor_speed != 0) {
    total_size += 1 + 4;
  }

  // float right_motor_speed = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_right_motor_speed = this->_internal_right_motor_speed();
  uint32_t raw_right_motor_speed;
  memcpy(&raw_right_motor_speed, &tmp_right_motor_speed, sizeof(tmp_right_motor_speed));
  if (raw_right_motor_speed != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MotorCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MotorCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MotorCommand::GetClassData() const { return &_class_data_; }


void MotorCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MotorCommand*>(&to_msg);
  auto& from = static_cast<const MotorCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproto.MotorCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_motor_speed = from._internal_left_motor_speed();
  uint32_t raw_left_motor_speed;
  memcpy(&raw_left_motor_speed, &tmp_left_motor_speed, sizeof(tmp_left_motor_speed));
  if (raw_left_motor_speed != 0) {
    _this->_internal_set_left_motor_speed(from._internal_left_motor_speed());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_right_motor_speed = from._internal_right_motor_speed();
  uint32_t raw_right_motor_speed;
  memcpy(&raw_right_motor_speed, &tmp_right_motor_speed, sizeof(tmp_right_motor_speed));
  if (raw_right_motor_speed != 0) {
    _this->_internal_set_right_motor_speed(from._internal_right_motor_speed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MotorCommand::CopyFrom(const MotorCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproto.MotorCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MotorCommand::IsInitialized() const {
  return true;
}

void MotorCommand::InternalSwap(MotorCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MotorCommand, _impl_.right_motor_speed_)
      + sizeof(MotorCommand::_impl_.right_motor_speed_)
      - PROTOBUF_FIELD_OFFSET(MotorCommand, _impl_.left_motor_speed_)>(
          reinterpret_cast<char*>(&_impl_.left_motor_speed_),
          reinterpret_cast<char*>(&other->_impl_.left_motor_speed_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MotorCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[0]);
}

// ===================================================================

class ArmCommand::_Internal {
 public:
};

ArmCommand::ArmCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myproto.ArmCommand)
}
ArmCommand::ArmCommand(const ArmCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ArmCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_dir_){}
    , decltype(_impl_.y_dir_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_dir_, &from._impl_.x_dir_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.y_dir_) -
    reinterpret_cast<char*>(&_impl_.x_dir_)) + sizeof(_impl_.y_dir_));
  // @@protoc_insertion_point(copy_constructor:myproto.ArmCommand)
}

inline void ArmCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_dir_){0}
    , decltype(_impl_.y_dir_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ArmCommand::~ArmCommand() {
  // @@protoc_insertion_point(destructor:myproto.ArmCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ArmCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ArmCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ArmCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:myproto.ArmCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_dir_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.y_dir_) -
      reinterpret_cast<char*>(&_impl_.x_dir_)) + sizeof(_impl_.y_dir_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArmCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x_dir = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_dir_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y_dir = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_dir_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ArmCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myproto.ArmCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x_dir = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_dir = this->_internal_x_dir();
  uint32_t raw_x_dir;
  memcpy(&raw_x_dir, &tmp_x_dir, sizeof(tmp_x_dir));
  if (raw_x_dir != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x_dir(), target);
  }

  // float y_dir = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_dir = this->_internal_y_dir();
  uint32_t raw_y_dir;
  memcpy(&raw_y_dir, &tmp_y_dir, sizeof(tmp_y_dir));
  if (raw_y_dir != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y_dir(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myproto.ArmCommand)
  return target;
}

size_t ArmCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myproto.ArmCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x_dir = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_dir = this->_internal_x_dir();
  uint32_t raw_x_dir;
  memcpy(&raw_x_dir, &tmp_x_dir, sizeof(tmp_x_dir));
  if (raw_x_dir != 0) {
    total_size += 1 + 4;
  }

  // float y_dir = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_dir = this->_internal_y_dir();
  uint32_t raw_y_dir;
  memcpy(&raw_y_dir, &tmp_y_dir, sizeof(tmp_y_dir));
  if (raw_y_dir != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArmCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ArmCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArmCommand::GetClassData() const { return &_class_data_; }


void ArmCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ArmCommand*>(&to_msg);
  auto& from = static_cast<const ArmCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproto.ArmCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x_dir = from._internal_x_dir();
  uint32_t raw_x_dir;
  memcpy(&raw_x_dir, &tmp_x_dir, sizeof(tmp_x_dir));
  if (raw_x_dir != 0) {
    _this->_internal_set_x_dir(from._internal_x_dir());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y_dir = from._internal_y_dir();
  uint32_t raw_y_dir;
  memcpy(&raw_y_dir, &tmp_y_dir, sizeof(tmp_y_dir));
  if (raw_y_dir != 0) {
    _this->_internal_set_y_dir(from._internal_y_dir());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ArmCommand::CopyFrom(const ArmCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproto.ArmCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArmCommand::IsInitialized() const {
  return true;
}

void ArmCommand::InternalSwap(ArmCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.y_dir_)
      + sizeof(ArmCommand::_impl_.y_dir_)
      - PROTOBUF_FIELD_OFFSET(ArmCommand, _impl_.x_dir_)>(
          reinterpret_cast<char*>(&_impl_.x_dir_),
          reinterpret_cast<char*>(&other->_impl_.x_dir_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ArmCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[1]);
}

// ===================================================================

class IntakeCommand::_Internal {
 public:
};

IntakeCommand::IntakeCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myproto.IntakeCommand)
}
IntakeCommand::IntakeCommand(const IntakeCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IntakeCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.speed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.speed_ = from._impl_.speed_;
  // @@protoc_insertion_point(copy_constructor:myproto.IntakeCommand)
}

inline void IntakeCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.speed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IntakeCommand::~IntakeCommand() {
  // @@protoc_insertion_point(destructor:myproto.IntakeCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IntakeCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IntakeCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IntakeCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:myproto.IntakeCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.speed_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IntakeCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float speed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IntakeCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myproto.IntakeCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float speed = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = this->_internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myproto.IntakeCommand)
  return target;
}

size_t IntakeCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myproto.IntakeCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float speed = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = this->_internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IntakeCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IntakeCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IntakeCommand::GetClassData() const { return &_class_data_; }


void IntakeCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IntakeCommand*>(&to_msg);
  auto& from = static_cast<const IntakeCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproto.IntakeCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_speed = from._internal_speed();
  uint32_t raw_speed;
  memcpy(&raw_speed, &tmp_speed, sizeof(tmp_speed));
  if (raw_speed != 0) {
    _this->_internal_set_speed(from._internal_speed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IntakeCommand::CopyFrom(const IntakeCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproto.IntakeCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntakeCommand::IsInitialized() const {
  return true;
}

void IntakeCommand::InternalSwap(IntakeCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.speed_, other->_impl_.speed_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IntakeCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[2]);
}

// ===================================================================

class ActuatorCommand::_Internal {
 public:
};

ActuatorCommand::ActuatorCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myproto.ActuatorCommand)
}
ActuatorCommand::ActuatorCommand(const ActuatorCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActuatorCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:myproto.ActuatorCommand)
}

inline void ActuatorCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ActuatorCommand::~ActuatorCommand() {
  // @@protoc_insertion_point(destructor:myproto.ActuatorCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActuatorCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActuatorCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActuatorCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:myproto.ActuatorCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActuatorCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActuatorCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myproto.ActuatorCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myproto.ActuatorCommand)
  return target;
}

size_t ActuatorCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myproto.ActuatorCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActuatorCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActuatorCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActuatorCommand::GetClassData() const { return &_class_data_; }


void ActuatorCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActuatorCommand*>(&to_msg);
  auto& from = static_cast<const ActuatorCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproto.ActuatorCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActuatorCommand::CopyFrom(const ActuatorCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproto.ActuatorCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActuatorCommand::IsInitialized() const {
  return true;
}

void ActuatorCommand::InternalSwap(ActuatorCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActuatorCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[3]);
}

// ===================================================================

class Wrapper::_Internal {
 public:
  static const ::myproto::MotorCommand& motor_command(const Wrapper* msg);
  static const ::myproto::ArmCommand& arm_command(const Wrapper* msg);
  static const ::myproto::IntakeCommand& intake_command(const Wrapper* msg);
  static const ::myproto::ActuatorCommand& actuator_command(const Wrapper* msg);
};

const ::myproto::MotorCommand&
Wrapper::_Internal::motor_command(const Wrapper* msg) {
  return *msg->_impl_.payload_.motor_command_;
}
const ::myproto::ArmCommand&
Wrapper::_Internal::arm_command(const Wrapper* msg) {
  return *msg->_impl_.payload_.arm_command_;
}
const ::myproto::IntakeCommand&
Wrapper::_Internal::intake_command(const Wrapper* msg) {
  return *msg->_impl_.payload_.intake_command_;
}
const ::myproto::ActuatorCommand&
Wrapper::_Internal::actuator_command(const Wrapper* msg) {
  return *msg->_impl_.payload_.actuator_command_;
}
void Wrapper::set_allocated_motor_command(::myproto::MotorCommand* motor_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (motor_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(motor_command);
    if (message_arena != submessage_arena) {
      motor_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, motor_command, submessage_arena);
    }
    set_has_motor_command();
    _impl_.payload_.motor_command_ = motor_command;
  }
  // @@protoc_insertion_point(field_set_allocated:myproto.Wrapper.motor_command)
}
void Wrapper::set_allocated_arm_command(::myproto::ArmCommand* arm_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (arm_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(arm_command);
    if (message_arena != submessage_arena) {
      arm_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, arm_command, submessage_arena);
    }
    set_has_arm_command();
    _impl_.payload_.arm_command_ = arm_command;
  }
  // @@protoc_insertion_point(field_set_allocated:myproto.Wrapper.arm_command)
}
void Wrapper::set_allocated_intake_command(::myproto::IntakeCommand* intake_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (intake_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(intake_command);
    if (message_arena != submessage_arena) {
      intake_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, intake_command, submessage_arena);
    }
    set_has_intake_command();
    _impl_.payload_.intake_command_ = intake_command;
  }
  // @@protoc_insertion_point(field_set_allocated:myproto.Wrapper.intake_command)
}
void Wrapper::set_allocated_actuator_command(::myproto::ActuatorCommand* actuator_command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (actuator_command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(actuator_command);
    if (message_arena != submessage_arena) {
      actuator_command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, actuator_command, submessage_arena);
    }
    set_has_actuator_command();
    _impl_.payload_.actuator_command_ = actuator_command;
  }
  // @@protoc_insertion_point(field_set_allocated:myproto.Wrapper.actuator_command)
}
Wrapper::Wrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myproto.Wrapper)
}
Wrapper::Wrapper(const Wrapper& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Wrapper* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.type_ = from._impl_.type_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kMotorCommand: {
      _this->_internal_mutable_motor_command()->::myproto::MotorCommand::MergeFrom(
          from._internal_motor_command());
      break;
    }
    case kArmCommand: {
      _this->_internal_mutable_arm_command()->::myproto::ArmCommand::MergeFrom(
          from._internal_arm_command());
      break;
    }
    case kIntakeCommand: {
      _this->_internal_mutable_intake_command()->::myproto::IntakeCommand::MergeFrom(
          from._internal_intake_command());
      break;
    }
    case kActuatorCommand: {
      _this->_internal_mutable_actuator_command()->::myproto::ActuatorCommand::MergeFrom(
          from._internal_actuator_command());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:myproto.Wrapper)
}

inline void Wrapper::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

Wrapper::~Wrapper() {
  // @@protoc_insertion_point(destructor:myproto.Wrapper)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Wrapper::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void Wrapper::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Wrapper::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:myproto.Wrapper)
  switch (payload_case()) {
    case kMotorCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.motor_command_;
      }
      break;
    }
    case kArmCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.arm_command_;
      }
      break;
    }
    case kIntakeCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.intake_command_;
      }
      break;
    }
    case kActuatorCommand: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.actuator_command_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Wrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:myproto.Wrapper)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Wrapper::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .myproto.MessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::myproto::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // .myproto.MotorCommand motor_command = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_motor_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .myproto.ArmCommand arm_command = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_arm_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .myproto.IntakeCommand intake_command = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_intake_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .myproto.ActuatorCommand actuator_command = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_actuator_command(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Wrapper::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myproto.Wrapper)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .myproto.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // .myproto.MotorCommand motor_command = 2;
  if (_internal_has_motor_command()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::motor_command(this),
        _Internal::motor_command(this).GetCachedSize(), target, stream);
  }

  // .myproto.ArmCommand arm_command = 3;
  if (_internal_has_arm_command()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::arm_command(this),
        _Internal::arm_command(this).GetCachedSize(), target, stream);
  }

  // .myproto.IntakeCommand intake_command = 4;
  if (_internal_has_intake_command()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::intake_command(this),
        _Internal::intake_command(this).GetCachedSize(), target, stream);
  }

  // .myproto.ActuatorCommand actuator_command = 5;
  if (_internal_has_actuator_command()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::actuator_command(this),
        _Internal::actuator_command(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myproto.Wrapper)
  return target;
}

size_t Wrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myproto.Wrapper)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .myproto.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  switch (payload_case()) {
    // .myproto.MotorCommand motor_command = 2;
    case kMotorCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.motor_command_);
      break;
    }
    // .myproto.ArmCommand arm_command = 3;
    case kArmCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.arm_command_);
      break;
    }
    // .myproto.IntakeCommand intake_command = 4;
    case kIntakeCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.intake_command_);
      break;
    }
    // .myproto.ActuatorCommand actuator_command = 5;
    case kActuatorCommand: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.actuator_command_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Wrapper::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Wrapper::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Wrapper::GetClassData() const { return &_class_data_; }


void Wrapper::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Wrapper*>(&to_msg);
  auto& from = static_cast<const Wrapper&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myproto.Wrapper)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  switch (from.payload_case()) {
    case kMotorCommand: {
      _this->_internal_mutable_motor_command()->::myproto::MotorCommand::MergeFrom(
          from._internal_motor_command());
      break;
    }
    case kArmCommand: {
      _this->_internal_mutable_arm_command()->::myproto::ArmCommand::MergeFrom(
          from._internal_arm_command());
      break;
    }
    case kIntakeCommand: {
      _this->_internal_mutable_intake_command()->::myproto::IntakeCommand::MergeFrom(
          from._internal_intake_command());
      break;
    }
    case kActuatorCommand: {
      _this->_internal_mutable_actuator_command()->::myproto::ActuatorCommand::MergeFrom(
          from._internal_actuator_command());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Wrapper::CopyFrom(const Wrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myproto.Wrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wrapper::IsInitialized() const {
  return true;
}

void Wrapper::InternalSwap(Wrapper* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.type_, other->_impl_.type_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Wrapper::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messages_2eproto_getter, &descriptor_table_messages_2eproto_once,
      file_level_metadata_messages_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace myproto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::myproto::MotorCommand*
Arena::CreateMaybeMessage< ::myproto::MotorCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myproto::MotorCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::myproto::ArmCommand*
Arena::CreateMaybeMessage< ::myproto::ArmCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myproto::ArmCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::myproto::IntakeCommand*
Arena::CreateMaybeMessage< ::myproto::IntakeCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myproto::IntakeCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::myproto::ActuatorCommand*
Arena::CreateMaybeMessage< ::myproto::ActuatorCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myproto::ActuatorCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::myproto::Wrapper*
Arena::CreateMaybeMessage< ::myproto::Wrapper >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myproto::Wrapper >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
