# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"C\n\x0cMotorCommand\x12\x18\n\x10left_motor_speed\x18\x01 \x01(\x02\x12\x19\n\x11right_motor_speed\x18\x02 \x01(\x02\"*\n\nArmCommand\x12\r\n\x05x_dir\x18\x01 \x01(\x02\x12\r\n\x05y_dir\x18\x02 \x01(\x02\"\x1e\n\rIntakeCommand\x12\r\n\x05speed\x18\x01 \x01(\x02\"\x1d\n\x0f\x41\x63tuatorCommand\x12\n\n\x02id\x18\x01 \x01(\x05\"\xd4\x01\n\x07Wrapper\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.MessageType\x12&\n\rmotor_command\x18\x02 \x01(\x0b\x32\r.MotorCommandH\x00\x12\"\n\x0b\x61rm_command\x18\x03 \x01(\x0b\x32\x0b.ArmCommandH\x00\x12(\n\x0eintake_command\x18\x04 \x01(\x0b\x32\x0e.IntakeCommandH\x00\x12,\n\x10\x61\x63tuator_command\x18\x05 \x01(\x0b\x32\x10.ActuatorCommandH\x00\x42\t\n\x07payload*h\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rMOTOR_COMMAND\x10\x01\x12\x0f\n\x0b\x41RM_COMMAND\x10\x02\x12\x12\n\x0eINTAKE_COMMAND\x10\x03\x12\x14\n\x10\x41\x43TUATOR_COMMAND\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=409
  _MESSAGETYPE._serialized_end=513
  _MOTORCOMMAND._serialized_start=18
  _MOTORCOMMAND._serialized_end=85
  _ARMCOMMAND._serialized_start=87
  _ARMCOMMAND._serialized_end=129
  _INTAKECOMMAND._serialized_start=131
  _INTAKECOMMAND._serialized_end=161
  _ACTUATORCOMMAND._serialized_start=163
  _ACTUATORCOMMAND._serialized_end=192
  _WRAPPER._serialized_start=195
  _WRAPPER._serialized_end=407
# @@protoc_insertion_point(module_scope)
