// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto;
namespace myproto {
class ActuatorCommand;
struct ActuatorCommandDefaultTypeInternal;
extern ActuatorCommandDefaultTypeInternal _ActuatorCommand_default_instance_;
class ArmCommand;
struct ArmCommandDefaultTypeInternal;
extern ArmCommandDefaultTypeInternal _ArmCommand_default_instance_;
class IntakeCommand;
struct IntakeCommandDefaultTypeInternal;
extern IntakeCommandDefaultTypeInternal _IntakeCommand_default_instance_;
class MotorCommand;
struct MotorCommandDefaultTypeInternal;
extern MotorCommandDefaultTypeInternal _MotorCommand_default_instance_;
class Wrapper;
struct WrapperDefaultTypeInternal;
extern WrapperDefaultTypeInternal _Wrapper_default_instance_;
}  // namespace myproto
PROTOBUF_NAMESPACE_OPEN
template<> ::myproto::ActuatorCommand* Arena::CreateMaybeMessage<::myproto::ActuatorCommand>(Arena*);
template<> ::myproto::ArmCommand* Arena::CreateMaybeMessage<::myproto::ArmCommand>(Arena*);
template<> ::myproto::IntakeCommand* Arena::CreateMaybeMessage<::myproto::IntakeCommand>(Arena*);
template<> ::myproto::MotorCommand* Arena::CreateMaybeMessage<::myproto::MotorCommand>(Arena*);
template<> ::myproto::Wrapper* Arena::CreateMaybeMessage<::myproto::Wrapper>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace myproto {

enum MessageType : int {
  UNKNOWN = 0,
  MOTOR_COMMAND = 1,
  ARM_COMMAND = 2,
  INTAKE_COMMAND = 3,
  ACTUATOR_COMMAND = 4,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = UNKNOWN;
constexpr MessageType MessageType_MAX = ACTUATOR_COMMAND;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class MotorCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myproto.MotorCommand) */ {
 public:
  inline MotorCommand() : MotorCommand(nullptr) {}
  ~MotorCommand() override;
  explicit PROTOBUF_CONSTEXPR MotorCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MotorCommand(const MotorCommand& from);
  MotorCommand(MotorCommand&& from) noexcept
    : MotorCommand() {
    *this = ::std::move(from);
  }

  inline MotorCommand& operator=(const MotorCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorCommand& operator=(MotorCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotorCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotorCommand* internal_default_instance() {
    return reinterpret_cast<const MotorCommand*>(
               &_MotorCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MotorCommand& a, MotorCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotorCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MotorCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MotorCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MotorCommand& from) {
    MotorCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myproto.MotorCommand";
  }
  protected:
  explicit MotorCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftMotorSpeedFieldNumber = 1,
    kRightMotorSpeedFieldNumber = 2,
  };
  // float left_motor_speed = 1;
  void clear_left_motor_speed();
  float left_motor_speed() const;
  void set_left_motor_speed(float value);
  private:
  float _internal_left_motor_speed() const;
  void _internal_set_left_motor_speed(float value);
  public:

  // float right_motor_speed = 2;
  void clear_right_motor_speed();
  float right_motor_speed() const;
  void set_right_motor_speed(float value);
  private:
  float _internal_right_motor_speed() const;
  void _internal_set_right_motor_speed(float value);
  public:

  // @@protoc_insertion_point(class_scope:myproto.MotorCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float left_motor_speed_;
    float right_motor_speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class ArmCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myproto.ArmCommand) */ {
 public:
  inline ArmCommand() : ArmCommand(nullptr) {}
  ~ArmCommand() override;
  explicit PROTOBUF_CONSTEXPR ArmCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ArmCommand(const ArmCommand& from);
  ArmCommand(ArmCommand&& from) noexcept
    : ArmCommand() {
    *this = ::std::move(from);
  }

  inline ArmCommand& operator=(const ArmCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArmCommand& operator=(ArmCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ArmCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const ArmCommand* internal_default_instance() {
    return reinterpret_cast<const ArmCommand*>(
               &_ArmCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ArmCommand& a, ArmCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(ArmCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ArmCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ArmCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ArmCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ArmCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ArmCommand& from) {
    ArmCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArmCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myproto.ArmCommand";
  }
  protected:
  explicit ArmCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXDirFieldNumber = 1,
    kYDirFieldNumber = 2,
  };
  // float x_dir = 1;
  void clear_x_dir();
  float x_dir() const;
  void set_x_dir(float value);
  private:
  float _internal_x_dir() const;
  void _internal_set_x_dir(float value);
  public:

  // float y_dir = 2;
  void clear_y_dir();
  float y_dir() const;
  void set_y_dir(float value);
  private:
  float _internal_y_dir() const;
  void _internal_set_y_dir(float value);
  public:

  // @@protoc_insertion_point(class_scope:myproto.ArmCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_dir_;
    float y_dir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class IntakeCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myproto.IntakeCommand) */ {
 public:
  inline IntakeCommand() : IntakeCommand(nullptr) {}
  ~IntakeCommand() override;
  explicit PROTOBUF_CONSTEXPR IntakeCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IntakeCommand(const IntakeCommand& from);
  IntakeCommand(IntakeCommand&& from) noexcept
    : IntakeCommand() {
    *this = ::std::move(from);
  }

  inline IntakeCommand& operator=(const IntakeCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntakeCommand& operator=(IntakeCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IntakeCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const IntakeCommand* internal_default_instance() {
    return reinterpret_cast<const IntakeCommand*>(
               &_IntakeCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IntakeCommand& a, IntakeCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(IntakeCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntakeCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IntakeCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IntakeCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IntakeCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IntakeCommand& from) {
    IntakeCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntakeCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myproto.IntakeCommand";
  }
  protected:
  explicit IntakeCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
  };
  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // @@protoc_insertion_point(class_scope:myproto.IntakeCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class ActuatorCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myproto.ActuatorCommand) */ {
 public:
  inline ActuatorCommand() : ActuatorCommand(nullptr) {}
  ~ActuatorCommand() override;
  explicit PROTOBUF_CONSTEXPR ActuatorCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActuatorCommand(const ActuatorCommand& from);
  ActuatorCommand(ActuatorCommand&& from) noexcept
    : ActuatorCommand() {
    *this = ::std::move(from);
  }

  inline ActuatorCommand& operator=(const ActuatorCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActuatorCommand& operator=(ActuatorCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActuatorCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActuatorCommand* internal_default_instance() {
    return reinterpret_cast<const ActuatorCommand*>(
               &_ActuatorCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ActuatorCommand& a, ActuatorCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(ActuatorCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActuatorCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActuatorCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActuatorCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActuatorCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ActuatorCommand& from) {
    ActuatorCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActuatorCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myproto.ActuatorCommand";
  }
  protected:
  explicit ActuatorCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:myproto.ActuatorCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Wrapper final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myproto.Wrapper) */ {
 public:
  inline Wrapper() : Wrapper(nullptr) {}
  ~Wrapper() override;
  explicit PROTOBUF_CONSTEXPR Wrapper(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Wrapper(const Wrapper& from);
  Wrapper(Wrapper&& from) noexcept
    : Wrapper() {
    *this = ::std::move(from);
  }

  inline Wrapper& operator=(const Wrapper& from) {
    CopyFrom(from);
    return *this;
  }
  inline Wrapper& operator=(Wrapper&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Wrapper& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kMotorCommand = 2,
    kArmCommand = 3,
    kIntakeCommand = 4,
    kActuatorCommand = 5,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Wrapper* internal_default_instance() {
    return reinterpret_cast<const Wrapper*>(
               &_Wrapper_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Wrapper& a, Wrapper& b) {
    a.Swap(&b);
  }
  inline void Swap(Wrapper* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Wrapper* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Wrapper* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Wrapper>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Wrapper& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Wrapper& from) {
    Wrapper::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Wrapper* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myproto.Wrapper";
  }
  protected:
  explicit Wrapper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kMotorCommandFieldNumber = 2,
    kArmCommandFieldNumber = 3,
    kIntakeCommandFieldNumber = 4,
    kActuatorCommandFieldNumber = 5,
  };
  // .myproto.MessageType type = 1;
  void clear_type();
  ::myproto::MessageType type() const;
  void set_type(::myproto::MessageType value);
  private:
  ::myproto::MessageType _internal_type() const;
  void _internal_set_type(::myproto::MessageType value);
  public:

  // .myproto.MotorCommand motor_command = 2;
  bool has_motor_command() const;
  private:
  bool _internal_has_motor_command() const;
  public:
  void clear_motor_command();
  const ::myproto::MotorCommand& motor_command() const;
  PROTOBUF_NODISCARD ::myproto::MotorCommand* release_motor_command();
  ::myproto::MotorCommand* mutable_motor_command();
  void set_allocated_motor_command(::myproto::MotorCommand* motor_command);
  private:
  const ::myproto::MotorCommand& _internal_motor_command() const;
  ::myproto::MotorCommand* _internal_mutable_motor_command();
  public:
  void unsafe_arena_set_allocated_motor_command(
      ::myproto::MotorCommand* motor_command);
  ::myproto::MotorCommand* unsafe_arena_release_motor_command();

  // .myproto.ArmCommand arm_command = 3;
  bool has_arm_command() const;
  private:
  bool _internal_has_arm_command() const;
  public:
  void clear_arm_command();
  const ::myproto::ArmCommand& arm_command() const;
  PROTOBUF_NODISCARD ::myproto::ArmCommand* release_arm_command();
  ::myproto::ArmCommand* mutable_arm_command();
  void set_allocated_arm_command(::myproto::ArmCommand* arm_command);
  private:
  const ::myproto::ArmCommand& _internal_arm_command() const;
  ::myproto::ArmCommand* _internal_mutable_arm_command();
  public:
  void unsafe_arena_set_allocated_arm_command(
      ::myproto::ArmCommand* arm_command);
  ::myproto::ArmCommand* unsafe_arena_release_arm_command();

  // .myproto.IntakeCommand intake_command = 4;
  bool has_intake_command() const;
  private:
  bool _internal_has_intake_command() const;
  public:
  void clear_intake_command();
  const ::myproto::IntakeCommand& intake_command() const;
  PROTOBUF_NODISCARD ::myproto::IntakeCommand* release_intake_command();
  ::myproto::IntakeCommand* mutable_intake_command();
  void set_allocated_intake_command(::myproto::IntakeCommand* intake_command);
  private:
  const ::myproto::IntakeCommand& _internal_intake_command() const;
  ::myproto::IntakeCommand* _internal_mutable_intake_command();
  public:
  void unsafe_arena_set_allocated_intake_command(
      ::myproto::IntakeCommand* intake_command);
  ::myproto::IntakeCommand* unsafe_arena_release_intake_command();

  // .myproto.ActuatorCommand actuator_command = 5;
  bool has_actuator_command() const;
  private:
  bool _internal_has_actuator_command() const;
  public:
  void clear_actuator_command();
  const ::myproto::ActuatorCommand& actuator_command() const;
  PROTOBUF_NODISCARD ::myproto::ActuatorCommand* release_actuator_command();
  ::myproto::ActuatorCommand* mutable_actuator_command();
  void set_allocated_actuator_command(::myproto::ActuatorCommand* actuator_command);
  private:
  const ::myproto::ActuatorCommand& _internal_actuator_command() const;
  ::myproto::ActuatorCommand* _internal_mutable_actuator_command();
  public:
  void unsafe_arena_set_allocated_actuator_command(
      ::myproto::ActuatorCommand* actuator_command);
  ::myproto::ActuatorCommand* unsafe_arena_release_actuator_command();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:myproto.Wrapper)
 private:
  class _Internal;
  void set_has_motor_command();
  void set_has_arm_command();
  void set_has_intake_command();
  void set_has_actuator_command();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::myproto::MotorCommand* motor_command_;
      ::myproto::ArmCommand* arm_command_;
      ::myproto::IntakeCommand* intake_command_;
      ::myproto::ActuatorCommand* actuator_command_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MotorCommand

// float left_motor_speed = 1;
inline void MotorCommand::clear_left_motor_speed() {
  _impl_.left_motor_speed_ = 0;
}
inline float MotorCommand::_internal_left_motor_speed() const {
  return _impl_.left_motor_speed_;
}
inline float MotorCommand::left_motor_speed() const {
  // @@protoc_insertion_point(field_get:myproto.MotorCommand.left_motor_speed)
  return _internal_left_motor_speed();
}
inline void MotorCommand::_internal_set_left_motor_speed(float value) {
  
  _impl_.left_motor_speed_ = value;
}
inline void MotorCommand::set_left_motor_speed(float value) {
  _internal_set_left_motor_speed(value);
  // @@protoc_insertion_point(field_set:myproto.MotorCommand.left_motor_speed)
}

// float right_motor_speed = 2;
inline void MotorCommand::clear_right_motor_speed() {
  _impl_.right_motor_speed_ = 0;
}
inline float MotorCommand::_internal_right_motor_speed() const {
  return _impl_.right_motor_speed_;
}
inline float MotorCommand::right_motor_speed() const {
  // @@protoc_insertion_point(field_get:myproto.MotorCommand.right_motor_speed)
  return _internal_right_motor_speed();
}
inline void MotorCommand::_internal_set_right_motor_speed(float value) {
  
  _impl_.right_motor_speed_ = value;
}
inline void MotorCommand::set_right_motor_speed(float value) {
  _internal_set_right_motor_speed(value);
  // @@protoc_insertion_point(field_set:myproto.MotorCommand.right_motor_speed)
}

// -------------------------------------------------------------------

// ArmCommand

// float x_dir = 1;
inline void ArmCommand::clear_x_dir() {
  _impl_.x_dir_ = 0;
}
inline float ArmCommand::_internal_x_dir() const {
  return _impl_.x_dir_;
}
inline float ArmCommand::x_dir() const {
  // @@protoc_insertion_point(field_get:myproto.ArmCommand.x_dir)
  return _internal_x_dir();
}
inline void ArmCommand::_internal_set_x_dir(float value) {
  
  _impl_.x_dir_ = value;
}
inline void ArmCommand::set_x_dir(float value) {
  _internal_set_x_dir(value);
  // @@protoc_insertion_point(field_set:myproto.ArmCommand.x_dir)
}

// float y_dir = 2;
inline void ArmCommand::clear_y_dir() {
  _impl_.y_dir_ = 0;
}
inline float ArmCommand::_internal_y_dir() const {
  return _impl_.y_dir_;
}
inline float ArmCommand::y_dir() const {
  // @@protoc_insertion_point(field_get:myproto.ArmCommand.y_dir)
  return _internal_y_dir();
}
inline void ArmCommand::_internal_set_y_dir(float value) {
  
  _impl_.y_dir_ = value;
}
inline void ArmCommand::set_y_dir(float value) {
  _internal_set_y_dir(value);
  // @@protoc_insertion_point(field_set:myproto.ArmCommand.y_dir)
}

// -------------------------------------------------------------------

// IntakeCommand

// float speed = 1;
inline void IntakeCommand::clear_speed() {
  _impl_.speed_ = 0;
}
inline float IntakeCommand::_internal_speed() const {
  return _impl_.speed_;
}
inline float IntakeCommand::speed() const {
  // @@protoc_insertion_point(field_get:myproto.IntakeCommand.speed)
  return _internal_speed();
}
inline void IntakeCommand::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void IntakeCommand::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:myproto.IntakeCommand.speed)
}

// -------------------------------------------------------------------

// ActuatorCommand

// int32 id = 1;
inline void ActuatorCommand::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t ActuatorCommand::_internal_id() const {
  return _impl_.id_;
}
inline int32_t ActuatorCommand::id() const {
  // @@protoc_insertion_point(field_get:myproto.ActuatorCommand.id)
  return _internal_id();
}
inline void ActuatorCommand::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void ActuatorCommand::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:myproto.ActuatorCommand.id)
}

// -------------------------------------------------------------------

// Wrapper

// .myproto.MessageType type = 1;
inline void Wrapper::clear_type() {
  _impl_.type_ = 0;
}
inline ::myproto::MessageType Wrapper::_internal_type() const {
  return static_cast< ::myproto::MessageType >(_impl_.type_);
}
inline ::myproto::MessageType Wrapper::type() const {
  // @@protoc_insertion_point(field_get:myproto.Wrapper.type)
  return _internal_type();
}
inline void Wrapper::_internal_set_type(::myproto::MessageType value) {
  
  _impl_.type_ = value;
}
inline void Wrapper::set_type(::myproto::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:myproto.Wrapper.type)
}

// .myproto.MotorCommand motor_command = 2;
inline bool Wrapper::_internal_has_motor_command() const {
  return payload_case() == kMotorCommand;
}
inline bool Wrapper::has_motor_command() const {
  return _internal_has_motor_command();
}
inline void Wrapper::set_has_motor_command() {
  _impl_._oneof_case_[0] = kMotorCommand;
}
inline void Wrapper::clear_motor_command() {
  if (_internal_has_motor_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.motor_command_;
    }
    clear_has_payload();
  }
}
inline ::myproto::MotorCommand* Wrapper::release_motor_command() {
  // @@protoc_insertion_point(field_release:myproto.Wrapper.motor_command)
  if (_internal_has_motor_command()) {
    clear_has_payload();
    ::myproto::MotorCommand* temp = _impl_.payload_.motor_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.motor_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::myproto::MotorCommand& Wrapper::_internal_motor_command() const {
  return _internal_has_motor_command()
      ? *_impl_.payload_.motor_command_
      : reinterpret_cast< ::myproto::MotorCommand&>(::myproto::_MotorCommand_default_instance_);
}
inline const ::myproto::MotorCommand& Wrapper::motor_command() const {
  // @@protoc_insertion_point(field_get:myproto.Wrapper.motor_command)
  return _internal_motor_command();
}
inline ::myproto::MotorCommand* Wrapper::unsafe_arena_release_motor_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:myproto.Wrapper.motor_command)
  if (_internal_has_motor_command()) {
    clear_has_payload();
    ::myproto::MotorCommand* temp = _impl_.payload_.motor_command_;
    _impl_.payload_.motor_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Wrapper::unsafe_arena_set_allocated_motor_command(::myproto::MotorCommand* motor_command) {
  clear_payload();
  if (motor_command) {
    set_has_motor_command();
    _impl_.payload_.motor_command_ = motor_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myproto.Wrapper.motor_command)
}
inline ::myproto::MotorCommand* Wrapper::_internal_mutable_motor_command() {
  if (!_internal_has_motor_command()) {
    clear_payload();
    set_has_motor_command();
    _impl_.payload_.motor_command_ = CreateMaybeMessage< ::myproto::MotorCommand >(GetArenaForAllocation());
  }
  return _impl_.payload_.motor_command_;
}
inline ::myproto::MotorCommand* Wrapper::mutable_motor_command() {
  ::myproto::MotorCommand* _msg = _internal_mutable_motor_command();
  // @@protoc_insertion_point(field_mutable:myproto.Wrapper.motor_command)
  return _msg;
}

// .myproto.ArmCommand arm_command = 3;
inline bool Wrapper::_internal_has_arm_command() const {
  return payload_case() == kArmCommand;
}
inline bool Wrapper::has_arm_command() const {
  return _internal_has_arm_command();
}
inline void Wrapper::set_has_arm_command() {
  _impl_._oneof_case_[0] = kArmCommand;
}
inline void Wrapper::clear_arm_command() {
  if (_internal_has_arm_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.arm_command_;
    }
    clear_has_payload();
  }
}
inline ::myproto::ArmCommand* Wrapper::release_arm_command() {
  // @@protoc_insertion_point(field_release:myproto.Wrapper.arm_command)
  if (_internal_has_arm_command()) {
    clear_has_payload();
    ::myproto::ArmCommand* temp = _impl_.payload_.arm_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.arm_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::myproto::ArmCommand& Wrapper::_internal_arm_command() const {
  return _internal_has_arm_command()
      ? *_impl_.payload_.arm_command_
      : reinterpret_cast< ::myproto::ArmCommand&>(::myproto::_ArmCommand_default_instance_);
}
inline const ::myproto::ArmCommand& Wrapper::arm_command() const {
  // @@protoc_insertion_point(field_get:myproto.Wrapper.arm_command)
  return _internal_arm_command();
}
inline ::myproto::ArmCommand* Wrapper::unsafe_arena_release_arm_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:myproto.Wrapper.arm_command)
  if (_internal_has_arm_command()) {
    clear_has_payload();
    ::myproto::ArmCommand* temp = _impl_.payload_.arm_command_;
    _impl_.payload_.arm_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Wrapper::unsafe_arena_set_allocated_arm_command(::myproto::ArmCommand* arm_command) {
  clear_payload();
  if (arm_command) {
    set_has_arm_command();
    _impl_.payload_.arm_command_ = arm_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myproto.Wrapper.arm_command)
}
inline ::myproto::ArmCommand* Wrapper::_internal_mutable_arm_command() {
  if (!_internal_has_arm_command()) {
    clear_payload();
    set_has_arm_command();
    _impl_.payload_.arm_command_ = CreateMaybeMessage< ::myproto::ArmCommand >(GetArenaForAllocation());
  }
  return _impl_.payload_.arm_command_;
}
inline ::myproto::ArmCommand* Wrapper::mutable_arm_command() {
  ::myproto::ArmCommand* _msg = _internal_mutable_arm_command();
  // @@protoc_insertion_point(field_mutable:myproto.Wrapper.arm_command)
  return _msg;
}

// .myproto.IntakeCommand intake_command = 4;
inline bool Wrapper::_internal_has_intake_command() const {
  return payload_case() == kIntakeCommand;
}
inline bool Wrapper::has_intake_command() const {
  return _internal_has_intake_command();
}
inline void Wrapper::set_has_intake_command() {
  _impl_._oneof_case_[0] = kIntakeCommand;
}
inline void Wrapper::clear_intake_command() {
  if (_internal_has_intake_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.intake_command_;
    }
    clear_has_payload();
  }
}
inline ::myproto::IntakeCommand* Wrapper::release_intake_command() {
  // @@protoc_insertion_point(field_release:myproto.Wrapper.intake_command)
  if (_internal_has_intake_command()) {
    clear_has_payload();
    ::myproto::IntakeCommand* temp = _impl_.payload_.intake_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.intake_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::myproto::IntakeCommand& Wrapper::_internal_intake_command() const {
  return _internal_has_intake_command()
      ? *_impl_.payload_.intake_command_
      : reinterpret_cast< ::myproto::IntakeCommand&>(::myproto::_IntakeCommand_default_instance_);
}
inline const ::myproto::IntakeCommand& Wrapper::intake_command() const {
  // @@protoc_insertion_point(field_get:myproto.Wrapper.intake_command)
  return _internal_intake_command();
}
inline ::myproto::IntakeCommand* Wrapper::unsafe_arena_release_intake_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:myproto.Wrapper.intake_command)
  if (_internal_has_intake_command()) {
    clear_has_payload();
    ::myproto::IntakeCommand* temp = _impl_.payload_.intake_command_;
    _impl_.payload_.intake_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Wrapper::unsafe_arena_set_allocated_intake_command(::myproto::IntakeCommand* intake_command) {
  clear_payload();
  if (intake_command) {
    set_has_intake_command();
    _impl_.payload_.intake_command_ = intake_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myproto.Wrapper.intake_command)
}
inline ::myproto::IntakeCommand* Wrapper::_internal_mutable_intake_command() {
  if (!_internal_has_intake_command()) {
    clear_payload();
    set_has_intake_command();
    _impl_.payload_.intake_command_ = CreateMaybeMessage< ::myproto::IntakeCommand >(GetArenaForAllocation());
  }
  return _impl_.payload_.intake_command_;
}
inline ::myproto::IntakeCommand* Wrapper::mutable_intake_command() {
  ::myproto::IntakeCommand* _msg = _internal_mutable_intake_command();
  // @@protoc_insertion_point(field_mutable:myproto.Wrapper.intake_command)
  return _msg;
}

// .myproto.ActuatorCommand actuator_command = 5;
inline bool Wrapper::_internal_has_actuator_command() const {
  return payload_case() == kActuatorCommand;
}
inline bool Wrapper::has_actuator_command() const {
  return _internal_has_actuator_command();
}
inline void Wrapper::set_has_actuator_command() {
  _impl_._oneof_case_[0] = kActuatorCommand;
}
inline void Wrapper::clear_actuator_command() {
  if (_internal_has_actuator_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.actuator_command_;
    }
    clear_has_payload();
  }
}
inline ::myproto::ActuatorCommand* Wrapper::release_actuator_command() {
  // @@protoc_insertion_point(field_release:myproto.Wrapper.actuator_command)
  if (_internal_has_actuator_command()) {
    clear_has_payload();
    ::myproto::ActuatorCommand* temp = _impl_.payload_.actuator_command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.actuator_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::myproto::ActuatorCommand& Wrapper::_internal_actuator_command() const {
  return _internal_has_actuator_command()
      ? *_impl_.payload_.actuator_command_
      : reinterpret_cast< ::myproto::ActuatorCommand&>(::myproto::_ActuatorCommand_default_instance_);
}
inline const ::myproto::ActuatorCommand& Wrapper::actuator_command() const {
  // @@protoc_insertion_point(field_get:myproto.Wrapper.actuator_command)
  return _internal_actuator_command();
}
inline ::myproto::ActuatorCommand* Wrapper::unsafe_arena_release_actuator_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:myproto.Wrapper.actuator_command)
  if (_internal_has_actuator_command()) {
    clear_has_payload();
    ::myproto::ActuatorCommand* temp = _impl_.payload_.actuator_command_;
    _impl_.payload_.actuator_command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Wrapper::unsafe_arena_set_allocated_actuator_command(::myproto::ActuatorCommand* actuator_command) {
  clear_payload();
  if (actuator_command) {
    set_has_actuator_command();
    _impl_.payload_.actuator_command_ = actuator_command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myproto.Wrapper.actuator_command)
}
inline ::myproto::ActuatorCommand* Wrapper::_internal_mutable_actuator_command() {
  if (!_internal_has_actuator_command()) {
    clear_payload();
    set_has_actuator_command();
    _impl_.payload_.actuator_command_ = CreateMaybeMessage< ::myproto::ActuatorCommand >(GetArenaForAllocation());
  }
  return _impl_.payload_.actuator_command_;
}
inline ::myproto::ActuatorCommand* Wrapper::mutable_actuator_command() {
  ::myproto::ActuatorCommand* _msg = _internal_mutable_actuator_command();
  // @@protoc_insertion_point(field_mutable:myproto.Wrapper.actuator_command)
  return _msg;
}

inline bool Wrapper::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Wrapper::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Wrapper::PayloadCase Wrapper::payload_case() const {
  return Wrapper::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace myproto

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::myproto::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::myproto::MessageType>() {
  return ::myproto::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
